fragment productFields on Product {
  id
  handle
  title
  onlineStoreUrl
  featuredImage {
    url
    altText
  }
  priceRange {
    ...productPriceRangeFields
  }
  variants(first: 12) {
    edges {
      node {
        title
        price {
          ...moneyV2Fields
        }
      }
    }
  }
}

query getProductsList {
  products(first: 12) {
    edges {
      node {
        ...productFields
      }
    }
  }
}

query getProductByHandle($handle: String) {
  product(handle: $handle) {
    ...productFields
  }
}
